### ISSUE TITLE
Build error for ios - duplicate symbols

### ISSUE THREAD

**Issue by mihirpatel** [dbaq/cordova-plugin-contacts-phone-numbers#18] opened 2015-10-17 17:47 UTC
duplicate symbol _OBJC_METACLASS_$_CDVAddressBookHelper in:
Objects-normal/i386/CDVContactsPhoneNumbers.o
Objects-normal/i386/CDVContacts.o

ld: 2 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

Version details:
echo "-> clang "; clang -v; echo "-> xcodebuild "; xcodebuild -version; echo "-> cordova " $(cordova -version); echo "-> ionic " $(ionic -version);

-> clang 
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
-> xcodebuild 
Xcode 7.0.1
Build version 7A1001
-> cordova  5.3.3
-> ionic  1.7.6

**Comment by dbaq** [comment] 2015-10-17 19:18
Hey @mihirpatel,

I was not able to reproduce. Here is what I've done and it is working fine:

* cordova create helloContacts2
* cd helloContacts2
* cordova plugin add https://github.com/dbaq/cordova-plugin-contacts-phone-numbers.git
* cordova platform add ios
* cordova build ios

Then opened the project in xcode and I was able to run it a simulator:
<img width="383" alt="screen shot 2015-10-17 at 12 13 23 pm" src="https://cloud.githubusercontent.com/assets/1867703/10560723/b364765c-74c8-11e5-8d94-d5b498b6191c.png">


Here is the information of the basic project:
```
$ cordova info
Collecting Data...


Node version: v0.12.7

Cordova version: 5.3.3

Config.xml file:

<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>HelloCordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" version="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
</widget>


Plugins:

com.dbaq.cordova.contactsPhoneNumbers,cordova-plugin-whitelist

iOS platform:

Xcode 7.0.1
Build version 7A1001
```

Please try to reproduce with the commands above, it might be a configuration issue on your project.

Cheers.

**Comment by mihirpatel** [comment] 2015-10-17 19:34
Hi @dbaq,

Thanks for quick reply. Does this plugin work in combination with cordova-plugin-contacts? Thinking how can I leverage pickContact along with the performance improvement you have for find contact.

Thanks!

**Comment by dbaq** [comment] 2015-10-17 20:59
That's an interesting use case that you have here. I'll look into it and try to reproduce it soon.

**Comment by mihirpatel** [comment] 2015-10-17 21:22
Changed CDVAddressBookHelper to CDVAddressBookPhoneNumberHelper in .h and .m files which resolved the issue.

sed -i '' 's/CDVAddressBookHelper/CDVAddressBookPhoneNumberHelper/g' src/ios/CDVContactsPhoneNumbers.h
sed -i '' 's/CDVAddressBookHelper/CDVAddressBookPhoneNumberHelper/g' src/ios/CDVContactsPhoneNumbers.m

**Comment by dbaq** [comment] 2015-10-17 21:26
Good job @mihirpatel, care to do a PR to fix the issue?

**Comment by mihirpatel** [comment] 2015-10-17 21:49
Just sent pull request: https://github.com/dbaq/cordova-plugin-contacts-phone-numbers/pull/19
Thanks!

**Comment by dbaq** [comment] 2015-10-17 21:50
And I just merged it. Thank you for your contribution.

**Closed by dbaq** 2015-10-17 21:50 UTC
Labels: bug
